apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secret-manager
  namespace: default
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-init
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: secret-manager
      restartPolicy: Never
      containers:
      - name: manager
        image: asia-southeast1-docker.pkg.dev/its-artifact-commons/please-protect/please-protect-jobs:v0.0.14
        command: ["ruby", "secrets-init.rb"]

        env:
        - name: SECRET_NAME
          value: "initial-secret"

        - name: RUN_MODE
          value: "once"
